if: branch = master
language: go
go: 1.12.x
sudo: true
git:
  depth: false
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_9f72dfef7328_key -iv $encrypted_9f72dfef7328_iv
  -in gcp-credentials.json.enc -out gcp-credentials.json -d
- git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
- source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
- source ${PULUMI_SCRIPTS}/ci/keep-failed-tests.sh
- sudo apt-get update && sudo apt-get install -y apt-transport-https
- curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
- sudo apt-get update
- sudo apt-get install -y kubectl
install:
- source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
- curl -L https://get.pulumi.com/ | bash
- export PATH=$HOME/.pulumi/bin:$PATH
- if [ ! -d $HOME/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- export PATH=$PATH:$HOME/google-cloud-sdk/bin
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- export GOOGLE_CREDENTIALS=$(cat gcp-credentials.json)
- gcloud auth activate-service-account --key-file gcp-credentials.json
- curl -o- -L https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
  | bash
- helm init -c
- helm repo add bitnami https://charts.bitnami.com/bitnami
- curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
- chmod +x ./aws-iam-authenticator
- mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator
-
before_script:
- "${PULUMI_SCRIPTS}/ci/ensure-dependencies"
jobs:
  include:
  - script: make travis_${TRAVIS_EVENT_TYPE}
  - stage: latest
    if: type = cron
    script: "${GOPATH}/src/github.com/pulumi/scripts/ci/run-at-head"
after_failure:
- "${PULUMI_SCRIPTS}/ci/upload-failed-tests"
notifications:
  webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
